CREATE TABLE herostats (
    id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id),
	strength INT NOT NULL,
    strmod INT NOT NULL,
    strsave INT NOT NULL,
    intelligence INT NOT NULL,
    intmod INT NOT NULL,
    intsave INT NOT NULL,
    dexterity INT NOT NULL,
    dexmod INT NOT NULL,
    dexsave INT NOT NULL,
    wisdom INT NOT NULL,
    wismod INT NOT NULL,
    wissave INT NOT NULL,
    constitution INT NOT NULL,
    conmod INT NOT NULL,
    consave INT NOT NULL,
    charisma INT NOT NULL,
    chamod INT NOT NULL,
    chasave INT NOT NULL,
    AC INT NOT NULL,
    speed INT NOT NULL,
    HP INT NOT NULL,
    proficiency INT NOT NULL,
    level INT NOT NULL,
    initiative INT NOT NULL,
    size VARCHAR(30) NOT NULL
)

CREATE TABLE barbarian (
	id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id),
    level INT(2) NOT NULL,
    proficiency INT(1) NOT NULL,
    feat INT(1) NOT NULL,
    health INT(10) NOT NULL,
    armor VARCHAR(300) NOT NULL,
    weapons VARCHAR(300) NOT NULL,
    tools VARCHAR(300) NOT NULL,
    saves VARCHAR(300) NOT NULL,
    skills VARCHAR(300) NOT NULL,
    rages INT(1) NOT NULL,
    EMD INT(1) NOT NULL,
    AC INT(2) NOT NULL,
    speed INT(3) NOT NULL,
    advantage VARCHAR(300) NOT NULL,
    immunities VARCHAR(300) NOT NULL,
    resistances VARCHAR(300) NOT NULL,
    classfeatures VARCHAR(300) NOT NULL
)


CREATE TABLE bard (
	id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id),
    level INT(2) NOT NULL,
    proficiency INT(1) NOT NULL,
    feat INT(1) NOT NULL,
    health INT(10) NOT NULL,
    armor VARCHAR(300) NOT NULL,
    weapons VARCHAR(300) NOT NULL,
    tools VARCHAR(300) NOT NULL,
    saves VARCHAR(300) NOT NULL,
    skills VARCHAR(300) NOT NULL,
    inspiration INT(1) NOT NULL,
    cantrips INT(1) NOT NULL,
    spells INT(2) NOT NULL,
    spellslot1 INT(1),
    spellslot2 INT(1),
    spellslot3 INT(1),
    spellslot4 INT(1),
    spellslot5 INT(1),
    spellslot6 INT(1),
    spellslot7 INT(1),
    spellslot8 INT(1),
    spellslot9 INT(1),
    EMD INT(1) NOT NULL,
    AC INT(2) NOT NULL,
    speed INT(3) NOT NULL,
    advantage VARCHAR(300) NOT NULL,
    immunities VARCHAR(300) NOT NULL,
    resistances VARCHAR(300) NOT NULL,
    classfeatures VARCHAR(300) NOT NULL
)

CREATE TABLE druid (
	id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id),
    level INT(2) NOT NULL,
    proficiency INT(1) NOT NULL,
    feat INT(1) NOT NULL,
    health INT(10) NOT NULL,
    armor VARCHAR(300) NOT NULL,
    weapons VARCHAR(300) NOT NULL,
    tools VARCHAR(300) NOT NULL,
    saves VARCHAR(300) NOT NULL,
    skills VARCHAR(300) NOT NULL,
    spellsprepared INT(1) NOT NULL,
    wildshape INT(1),
    cantrips INT(1) NOT NULL,
    spellsaveDC INT(20) NOT NULL,
    spellattack INT(30) NOT NULL,
    spellslot1 INT(1),
    spellslot2 INT(1),
    spellslot3 INT(1),
    spellslot4 INT(1),
    spellslot5 INT(1),
    spellslot6 INT(1),
    spellslot7 INT(1),
    spellslot8 INT(1),
    spellslot9 INT(1),
    circlespells VARCHAR(300) NOT NULL,
    EMD INT(1) NOT NULL,
    AC INT(2) NOT NULL,
    speed INT(3) NOT NULL,
    advantage VARCHAR(300) NOT NULL,
    immunities VARCHAR(300) NOT NULL,
    resistances VARCHAR(300) NOT NULL,
    classfeatures VARCHAR(300) NOT NULL
)

CREATE TABLE fighter (
	id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id),
    level INT(2) NOT NULL,
    proficiency INT(1) NOT NULL,
    feat INT(1) NOT NULL,
    health INT(10) NOT NULL,
    armor VARCHAR(300) NOT NULL,
    weapons VARCHAR(300) NOT NULL,
    tools VARCHAR(300) NOT NULL,
    saves VARCHAR(300) NOT NULL,
    skills VARCHAR(300) NOT NULL,
    maneuvers INT(1),
    maneuverDC INT(2),
    superiority INT(2) NOT NULL,
    style VARCHAR(30) NOT NULL,
    cantrips INT(1) NOT NULL,
    spellsKnown INT(2) NOT NULL,
    spellsaveDC INT(20) NOT NULL,
    spellattack INT(30) NOT NULL,
    spellslot1 INT(1),
    spellslot2 INT(1),
    spellslot3 INT(1),
    spellslot4 INT(1),
    EMD INT(1) NOT NULL,
    AC INT(2) NOT NULL,
    speed INT(3) NOT NULL,
	advantage VARCHAR(300) NOT NULL,
    immunities VARCHAR(300) NOT NULL,
    resistances VARCHAR(300) NOT NULL,
    classfeatures VARCHAR(300) NOT NULL,
    extrastyle VARCHAR(300) NOT NULL
)
